### ISSUE TITLE
Inconsistent length of services

### ISSUE THREAD

**Issue by denizs** [figo-connect/python-figo#38]
While working on the error code feature, I noticed that the CI tests were failing because of ` test_03_get_supported_payment_services`. Apparently, the length of services had changed from 28 to 27.

After @fricklerhandwerk just merged my PR (#37), the travis build started failing again because of the very same test, now complaining that `len(services)` was evaluated to 28 😦 .

**Comment by berend** [comment]
That test is very old and is not testing the SDK at test. Services are our supported financial providers - a list that grows. Asserting a fixed length is wrong and will be corrected.

Also, other tests are flaky, because they are running against a staging server(configured by encrypted values in .travis.yml) and the connection from travis to our staging sometimes times out. We are investigating this and working on a better test suite, that also ensures that the SDK work with a real api and not just some mocked responses.

**Comment by denizs** [comment]
Thanks for the clarification! Already figured that this was merely a poor test rather than a major bug 👻

LMK if I can help, I'd like to get more involved with this project. :octocat:
