### ISSUE TITLE
Spammy logs due to ssl fingerprint

### ISSUE THREAD

**Issue by holger-zeit** [figo-connect/python-figo#52]
Hi,
I created a small PR #51 to add the old ssl fingerprint.
Half of our logs are because of this and I'd love to not see them anymore :)

Let me know if this is acceptable or what you propose to fix this.
Thanks :)

**Comment by zyv** [comment]
@berend @achimsen this is now obsolete.

**Comment by zyv** [comment]
(#51 should be rejected accordingly)

**Comment by berend** [comment]
Thanks @zyv.

Note: This is currently only fixed, because the latest fingerprint switch is completed (as of 25th of june) and currently we only have one fingerprint (the current one).  On the next switch, there will be two again (old and new, to allow a fluent transition) and this issue will rise again - if it is not fixed then.

**Comment by zyv** [comment]
I would question the meaningfulness of this logging statement, but it can be replaced with a `warnings.warn` / `once` filter, which can also be overridden by user. Want a PR?

**Comment by berend** [comment]
Sure!

As hint: If I remember correctly the log statement was caused by having two fingerprints (old and current, resp. current and upcoming) and that log entry was caused by one of the two that does not match. So, there should only be a log entry if none of the given fingerprints (even if there are more then two) matches - then the connection should fail anyway...
